import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import DashboardCards from "./dashboard/dashboardCards";
import DashboardPatientGraphs from "./dashboard/dashboardPatientsGraphs";
import DashboardInventoryGraphs from "./dashboard/dashboardInventoryGraphs";
import DashboardPieCard from "./dashboard/dashboardPieCard";
import CardsSkeleton from "../components/loading/cardSkeleton";
import PieCardSkeleton from "../components/loading/pieCardSkeleton";
import ChartSkeleton from "../components/loading/chartSkeleton";
import {
  getDashboardSummary,
  getPatientTrends,
  getDiagnosisDistribution,
  getTopMedicines,
} from "../services/dashboardService";
import "../styles/dashboard.css";

function Dashboard() {
  const [summary, setSummary] = useState({});
  const [patientTrends, setPatientTrends] = useState([]);
  const currentYear = new Date().getFullYear();

  const [selectedYear, setSelectedYear] = useState(currentYear);
  const [diagnosisData, setDiagnosisData] = useState([]);
  const [topMedicines, setTopMedicines] = useState([]);

  const [loading, setLoading] = useState(true);
  const [showPreview, setShowPreview] = useState(false);
  const [pdfPreview, setPdfPreview] = useState("");
  const handleExportPDF = async () => {
    const pdf = new jsPDF("p", "mm", "a4");

    const pageWidth = pdf.internal.pageSize.getWidth();

    // HEADER
    pdf.setFontSize(20);
    pdf.text("Medical Dashboard Report", pageWidth / 2, 20, {
      align: "center",
    });

    pdf.setFontSize(10);
    pdf.text(`Generated on ${new Date().toLocaleString()}`, pageWidth / 2, 28, {
      align: "center",
    });

    // SUMMARY SECTION
    pdf.setFontSize(14);
    pdf.text("Dashboard Summary", 14, 45);

    autoTable(pdf, {
      startY: 50,
      head: [["Metric", "Value"]],
      body: [
        ["Total Patients", summary.totalPatients || 0],
        ["Consulted Patients", summary.consultedPatients || 0],
        ["Pending Patients", summary.pendingPatients || 0],
        ["Medicines Low Stock", summary.lowStockMedicines || 0],
      ],
    });

    // DIAGNOSIS DISTRIBUTION
    pdf.setFontSize(14);
    pdf.text("Diagnosis Distribution", 14, pdf.lastAutoTable.finalY + 15);

    autoTable(pdf, {
      startY: pdf.lastAutoTable.finalY + 20,
      head: [["Diagnosis", "Count"]],
      body: diagnosisData.map((item) => [item.name, item.value]),
    });

    // MEDICINES
    pdf.setFontSize(14);
    pdf.text("Top Prescribed Medicines", 14, pdf.lastAutoTable.finalY + 15);

    autoTable(pdf, {
      startY: pdf.lastAutoTable.finalY + 20,
      head: [["Medicine", "Prescriptions"]],
      body: topMedicines.map((item) => [item.medicine, item.count]),
    });

    // FOOTER
    pdf.setFontSize(9);
    pdf.text("Generated by Medical Dashboard System", pageWidth / 2, 285, {
      align: "center",
    });

    // CREATE PREVIEW URL
    const blob = pdf.output("blob");
    const url = URL.createObjectURL(blob);

    setPdfPreview(url);
    setShowPreview(true);
  };
  useEffect(() => {
    const loadDashboard = async () => {
      try {
        const [summaryData, trendsData, diagnosisResult, medicinesResult] =
          await Promise.all([
            getDashboardSummary(),
            getPatientTrends(selectedYear),
            getDiagnosisDistribution(),
            getTopMedicines(),
          ]);

        setSummary(summaryData);
        setPatientTrends(trendsData);
        setDiagnosisData(diagnosisResult);
        setTopMedicines(medicinesResult);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    loadDashboard();
  }, [selectedYear]);

  return (
    <div className="dashboard-page">
      <div className="dashboard-header">
        <div>
          <h1>Dashboard</h1>
        </div>

        <button className="publish-btn" onClick={handleExportPDF}>
          Export
        </button>
      </div>

      {loading ? <CardsSkeleton /> : <DashboardCards summary={summary} />}

      <div className="dashboard-middle-row">
        {loading ? (
          <>
            <PieCardSkeleton />
            <PieCardSkeleton />
          </>
        ) : (
          <>
            <DashboardPieCard
              title="Diagnosis Distribution"
              data={diagnosisData}
              labelKey="name"
              valueKey="value"
            />

            <DashboardPieCard
              title="Prescribed Medicines"
              data={topMedicines}
              labelKey="medicine"
              valueKey="count"
            />
          </>
        )}
      </div>

      {loading ? (
        <ChartSkeleton />
      ) : (
        <DashboardPatientGraphs
          patientTrends={patientTrends}
          diagnosisData={diagnosisData}
          selectedYear={selectedYear}
          setSelectedYear={setSelectedYear}
          currentYear={currentYear}
        />
      )}
      {showPreview && (
        <div className="pdf-preview-overlay">
          <div className="pdf-preview-modal">
            <div className="pdf-preview-header">
              <h2>PDF Preview</h2>

              <div className="preview-actions">
                <button onClick={() => window.open(pdfPreview)}>
                  Download PDF
                </button>

                <button onClick={() => setShowPreview(false)}>Close</button>
              </div>
            </div>

            <iframe
              src={pdfPreview}
              title="PDF Preview"
              width="100%"
              height="700"
            />
          </div>
        </div>
      )}
    </div>
  );
}

export default Dashboard;
